### PR TITLE
Store CMS media in Swift

### PR DESCRIPTION
**Pull request by nottrobin**
- Add settings to store CMS media assets under `/media`
- If `OS_TENANT_NAME`, `OS_AUTH_URL`, `OS_USERNAME`, `OS_PASSWORD` and `OS_REGION_NAME` are provided, use these to connect to swift
- If swift credentials are missing, throw an error, unless in debug mode
- If in debug mode and no swift creds are provided, use local `media` directory
### Debug on

```
make run
```

You should see "No swift credentials found. Using local `media` directory for CMS media."
### Debug off, no swift

```
DJANGO_DEBUG=false make run
```

You should see "EnvironmentError: [ERROR]: No swift credentials found - required for CMS media."
### Swift

Find your swift credentials in `novarc` in your [canonistack credentials](https://enigma.admin.canonical.com/user/+me/canonistack-credentials.zip).

Now add the `OS_` environment variables from the `novarc` file to the `.env` file inside developer.ubuntu.com, and remove any `"` quotation marks, so it looks like this:

``` bash
PORT=8017
DB=true
OS_USERNAME=robin
OS_TENANT_NAME=robin_project
OS_PASSWORD=xxxxxxxx
OS_AUTH_URL=https://keystone.canonistack.canonical.com:443/v2.0/
OS_REGION_NAME=lcy01
```

Now get inside the Django container:

``` bash
make "docker-compose run --service-ports --entrypoint /bin/bash webapp"
```

Now import all docs data:

``` bash
./update_apidocs.sh
```

Let it run for about 30 seconds then cancel it. Quit the image, and run:

``` bash
rm -rf media  # Delete any local media to make sure its definitely using swift
make run      # Run the server
```

Check you see "Swift credentials found".

When the server starts up again, visit http://127.0.0.1:8017/media/api/apps/qml/sdk-15.04.5/QtQml.Qt/images/declarative-rect_tint.png and check it exists.

### CODE REVIEW

**Comment by nottrobin** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;tqrOoZp1&#x2F;1374-mojo-spec-use-swift-account-for-cms-media-storage"> Mojo spec: Use swift account for CMS media storage</a>

**Comment by WillMoggridge** [comment]
I seem to be having a problem with importing sanitizer from html5lib.

Issue seems reported here: https://github.com/divio/djangocms-text-ckeditor/issues/336

**Comment by anthonydillon** [comment]
What is the plan for this PR?

**Comment by nottrobin** [comment]
@anthonydillon to leave it here, open, and never merge it. Mostly to irritate you.

**Comment by deadlight** [comment]
@nottrobin I'm going to close this, to keep our PR list clean.

**Pull request closed without merging**
